### ISSUE TITLE
github.com cannot be opened !

### ISSUE THREAD

**Issue by shivakumargn** [sirnewton01/godev#6] opened 2013-11-27 02:05 UTC
Within $GOPATH/src all packages that have sub-directories open just fine.
_Only_ github.com seems to have a problem that it brings up below message:

```
Use the [+] to create new files and folders. Click a file to start coding.
```

I renamed github.com to github_com and tried again. Now github_com opens properly just like any other folder without problem.

**Comment by sirnewton01** [comment] 2013-11-27 15:02
Thanks for reporting this.

I'm assuming that you're seeing this on Windows? Is there anything special about your GOPATH (eg. spaces, unusual characters)?

**Comment by shivakumargn** [comment] 2013-11-27 15:14
My gopath has multiple actual paths separated by ";".

I find the issue strange since this problem did not exist for bitbucket.org which has similar pattern as that of github packages.

**Comment by sirnewton01** [comment] 2013-11-27 20:54
Unfortunately, I am unable to reproduce the problem on my Windows VM. Can you try again with a simpler GOPATH to see if the problem still exists? Can you provide me with more details about your GOPATH and what packages are in each so I can try to reproduce this again?

Thank you,
Chris

**Comment by sirnewton01** [comment] 2013-12-23 00:42
Closing this for now. Please re-open when you can provide more details to help track down the bug.

**Closed as completed by sirnewton01** 2013-12-23 00:42 UTC
